# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 524)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../.designer/backup/resources/logo2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(16, 16))
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.classTab = QtWidgets.QWidget()
        self.classTab.setObjectName("classTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.classTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loadConceptsButton = QtWidgets.QPushButton(self.classTab)
        self.loadConceptsButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadConceptsButton.sizePolicy().hasHeightForWidth())
        self.loadConceptsButton.setSizePolicy(sizePolicy)
        self.loadConceptsButton.setAutoFillBackground(False)
        self.loadConceptsButton.setDefault(False)
        self.loadConceptsButton.setFlat(False)
        self.loadConceptsButton.setObjectName("loadConceptsButton")
        self.horizontalLayout_3.addWidget(self.loadConceptsButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.classTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_2.setStyleSheet("")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.classesTab = QtWidgets.QWidget()
        self.classesTab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.classesTab.setObjectName("classesTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.classesTab)
        self.gridLayout_4.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.classesListWidget_2 = QtWidgets.QListWidget(self.classesTab)
        self.classesListWidget_2.setStyleSheet("")
        self.classesListWidget_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.classesListWidget_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.classesListWidget_2.setAlternatingRowColors(False)
        self.classesListWidget_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.classesListWidget_2.setMovement(QtWidgets.QListView.Static)
        self.classesListWidget_2.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.classesListWidget_2.setObjectName("classesListWidget_2")
        self.gridLayout_4.addWidget(self.classesListWidget_2, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.classesTab, "")
        self.conceptsTab = QtWidgets.QWidget()
        self.conceptsTab.setObjectName("conceptsTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.conceptsTab)
        self.verticalLayout_7.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.clearFieldsButton = QtWidgets.QPushButton(self.conceptsTab)
        self.clearFieldsButton.setDefault(False)
        self.clearFieldsButton.setFlat(False)
        self.clearFieldsButton.setObjectName("clearFieldsButton")
        self.verticalLayout_7.addWidget(self.clearFieldsButton)
        self.scrollArea = QtWidgets.QScrollArea(self.conceptsTab)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 400, 325))
        self.scrollAreaWidgetContents.setStyleSheet("font-size: 14px;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.tabWidget_2.addTab(self.conceptsTab, "")
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.determineClassButton = QtWidgets.QPushButton(self.classTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.determineClassButton.sizePolicy().hasHeightForWidth())
        self.determineClassButton.setSizePolicy(sizePolicy)
        self.determineClassButton.setDefault(False)
        self.determineClassButton.setFlat(False)
        self.determineClassButton.setObjectName("determineClassButton")
        self.verticalLayout.addWidget(self.determineClassButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.classTab)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("margin-top:45px;")
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.characterNameLabel = QtWidgets.QLabel(self.classTab)
        self.characterNameLabel.setStyleSheet("font: 40pt;")
        self.characterNameLabel.setText("")
        self.characterNameLabel.setObjectName("characterNameLabel")
        self.verticalLayout_2.addWidget(self.characterNameLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.classTab, "")
        self.modelTab = QtWidgets.QWidget()
        self.modelTab.setObjectName("modelTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.modelTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.importModelButton = QtWidgets.QPushButton(self.modelTab)
        self.importModelButton.setObjectName("importModelButton")
        self.horizontalLayout_2.addWidget(self.importModelButton)
        self.exportModelButton = QtWidgets.QPushButton(self.modelTab)
        self.exportModelButton.setObjectName("exportModelButton")
        self.horizontalLayout_2.addWidget(self.exportModelButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.modelTable = QtWidgets.QTableWidget(self.modelTab)
        self.modelTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.modelTable.setObjectName("modelTable")
        self.modelTable.setColumnCount(0)
        self.modelTable.setRowCount(0)
        self.verticalLayout_4.addWidget(self.modelTable)
        self.tabWidget.addTab(self.modelTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Overwatch Classifier"))
        self.loadConceptsButton.setText(_translate("MainWindow", "Загрузить концепты и классы"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.classesTab), _translate("MainWindow", "Классы"))
        self.clearFieldsButton.setText(_translate("MainWindow", "Очистить поля"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.conceptsTab), _translate("MainWindow", "Концепты"))
        self.determineClassButton.setText(_translate("MainWindow", "Узнать класс"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.classTab), _translate("MainWindow", "Классификация"))
        self.importModelButton.setText(_translate("MainWindow", "Загрузить модель"))
        self.exportModelButton.setText(_translate("MainWindow", "Выгрузить модель"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.modelTab), _translate("MainWindow", "База знаний"))

